[package]
name = "archive-sys"
description = "Rust bindings to libarchive"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
anyhow = "1.0.90"
bindgen = "0.70.1"
pkg-config = "0.3.31"
